name: aquanetviet
favicon: null
layout_spectrum: 0.00271
typography_spectrum: 1
title: Vietnam Aquaculture Network
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f9dff'
    - '#27006b'
    - '#232323'
    - '#ffffff'
    - '#b6dcff'
  brandStrength: 0.702509
  lightness: 0.7821058
  saturation: 0.3837345
  rhythmicContrast: 0.6057348
purpose: []
