name: aquanetviet
favicon: null
layout_spectrum: 0.73442
typography_spectrum: 1
title: Mạng Thủy sản Việt Nam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6898437
  lightness: 0.7821058
  saturation: 0.3837345
  rhythmicContrast: 0.6057348
purpose: []
